### ISSUE TITLE
Support `bucketVersion` kwarg for `FeatureRule`

### ISSUE THREAD

**Issue by brycethornton** [growthbook/growthbook-python#15]
When I call `gb.load_features()` for our account I get an exception:

`TypeError: FeatureRule.__init__() got an unexpected keyword argument 'bucketVersion'`

It looks like one of our features has a rule that includes a `bucketVersion` key which isn't supported in the `FeatureRule.__init__()`.

```
our_feature: {'defaultValue': False, 'rules': [{'force': True}, {'coverage': 1, 'hashAttribute': 'deviceId', 'bucketVersion': 1, 'seed': 'abc123', 'hashVersion': 2, 'force': True}]}
```

Is there a way to workaround this for now until this is added? For right now I only need access to one feature (not the one causing the issue).

**Comment by vaibhavi3t** [comment]
I'm also facing same issue from Feb 29. with error msg

`error __init__() got an unexpected keyword argument 'bucketVersion'`

Is there any workaround or fix for this?
