### ISSUE TITLE
[Bug] mypy error due to PEP-561 incompatibility

### ISSUE THREAD

**Issue by august-growthbook** [growthbook/growthbook-python#17]
Reporting this from a customer:

The Python SDK [has type hints](https://github.com/growthbook/growthbook-python/blob/main/growthbook.py) but it looks like the library isn't [PEP-561 compatible](https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages) so we're getting the following mypy error:

```
bases/verifications/approval_service/bootstrap.py:7: error: Skipping analyzing "growthbook": module is installed, but missing library stubs or py.typed marker  [import-untyped]
bases/verifications/approval_service/bootstrap.py:7: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 208 source files)
```

Are there any plans to release make the library PEP-561 compatible?

**Comment by vazarkevych** [comment]
The issue was closed after the solution was merged in the pull request.
