### ISSUE TITLE
Improve handling of service unavailibility

### ISSUE THREAD

**Issue by Nikolay-Andreychuk** [growthbook/growthbook-python#21]
# Context
If Growthbook is temporarily unavailable, I want to use the most recent feature state available to me. 
It's important to avoid falling back to a default value or feature states that are too old because there are cases when this leads to an outage. 
For example, if we have a feature flag that adds a required field to an external contract and 50% of users use an old contract, then:
- switching everyone to false will lead to a loss of field value for 50% of users
- switching everyone to true will lead to request errors for another 50% of users

Caching is not a robust solution to the problem. If the cache is expired and Growthbook is unavailable, then:
1. Any feature evaluation will return the default value.
2. Any call to `GrowthBook.load_features` will take a bit more time wait until a timeout and retry several times), increasing the response time of all services that use Growthbook
And if we set large expiration time for a cache, configuration will be updated rarely.

Growthbook Proxy doesn't solve the problem fully, as the proxy itself becomes a single failure point.

Currently, it's possible to solve the problem by overriding the cache with one that:
1. Saves feature configuration to memory without expiration.
2. Reloads feature configuration every 60 seconds in a background thread.
3. As a fallback, load feature configuration from disk (we can put this file to docker container during release) or another alternative source. 

[Here](https://github.com/Nikolay-Andreychuk/feature-flag-services-playground/pull/2/files#diff-df5184bf1f67239fcedd4578cd15b7c94f3f765feabd09c5f20b5831bca33903R14-R76) is an example.

However, this solution relies on the current internals of SDK implementation, and it would be better to have such an option pre-built in a library.

# Possible solution
1. Update the feature state in a background thread instead of calling load_features each time. 
2. Use a stale feature state from memory even if it hasn't been updated for a long time.
3. Add an option to load feature configuration from an alternative source if Growthbook is unavailable when application starts.

# Additiona links
[Repository](https://github.com/Nikolay-Andreychuk/feature-flag-services-playground/pull/2/files) with reproduction of the problem.

**Comment by vazarkevych** [comment]
Hi, @Nikolay-Andreychuk.  We added an SSE connection to the SDK and hope that this will help resolve the issue. We will provide a pull request as soon as possible.

**Comment by vazarkevych** [comment]
Hi, @Nikolay-Andreychuk. We merge pull request with latest changes [](https://github.com/growthbook/growthbook-python/pull/23)
